export const GET_RATINGS = "DICTIONARIES/GET_RATINGS"
export const GET_USERS = "USERS/GET_ALL_USERS"
export const CREATE_USER = "USERS/CREATE_USER"
export const REMOVE_USER = "USERS/REMOVE_USER"

export const SHOW_MODAL_CREATE_USER = "MODAL/SHOW_MODAL_CREATE_USER"
export const SHOW_MODAL_EDIT_USER = "MODAL/SHOW_MODAL_EDIT_USER"
export const HIDE_MODAL = "MODAL/HIDE_MODAL"